### ISSUE TITLE
CPU Info on Nerves doesn't works

### ISSUE THREAD

**Issue by zacky1972** [zeam-vm/cpu_info#1]
CPU Info on Nerves doesn't work because Nerves is minimized and hasn't `sort`, `wc` and etc. commands!
Next version of CPU Info will support Nerves.

The following functions are required at least:

* visible /proc/cpuinfo
* visible /etc/issue
* able to use `uname`

The minimum requirement are satisfied by Nerves?

**Comment by fhunleth** [comment]
Nerves has `/proc/cpuinfo`.

For `/etc/issue`, I think that you want [`/etc/os-release`](https://www.freedesktop.org/software/systemd/man/os-release.html) instead. Some system admins customize `/etc/issue` since it's displayed at login prompts.

```elixir
iex(1)> File.read!("/etc/os-release") |> IO.puts
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

On Nerves:

```elixir
iex(1)> File.read!("/etc/os-release") |> IO.puts
NAME=Buildroot
VERSION=2019.08.1
ID=buildroot
VERSION_ID=2019.08.1
PRETTY_NAME="Buildroot 2019.08.1"
```

For `uname`, try:

```elixir
iex(1)> File.read("/proc/sys/kernel/osrelease")
{:ok, "4.19.50\n"}
iex(2)> File.read("/proc/sys/kernel/ostype")
{:ok, "Linux\n"}
iex(3)> File.read("/proc/sys/kernel/version")
{:ok, "#1 PREEMPT Mon Oct 28 20:21:43 UTC 2019\n"}
```

Those are, of course, Linux only. I think that I'd try running `uname` first and then read from `/proc`.

**Comment by zacky1972** [comment]
Thank you, @fhunleth 

Also thank you, @TORIFUKUKaiou and @osako_ricc , for corporation for debugging it on Nerves!
